# Tools for programming

## Github

### Introduction

GitHub is a platform for hosting, storing, and editing code. It facilitates projects organization and team collaboration. The platform is built around "Repositories" used to organize code for projects. 

Here is the official website: [https://github.com/](https://github.com/).

MBAn students will use Github for team projects in <MBAn501 Team and software management> in the summer term. And students can also find many resources about programming on the platform. 

### Main features

- Hold code in repositories 
Users use Github to hold and organize projects. All the code and documentation are stored in "Repositories". There are many tools and features for users to customize their repositories and manage their projects. 

| Tools | Details |
| :--- | :--- |
| Add collaborators | Developers and project managers can work on projects together in Github using the "Add collaborators" tool. |
| Issue | Developers and project managers can collect user feedbacks and organize tasks using the "issue" feature. They can also use it to priorize issues. |
| Branch | Developers can create a “branch” to work on their changes. Once they've finished, they can merge the branch back into the master branch. |

- Version control of Github
Version control of Github tracks what and when each developer changes, and allows users to roll back individual changes without affecting other changes down the timeline. 

- Open-source projects resources
GitHub is one of the largest communities for the world's top developers, where you can find almost anything you want. There are many great, famous open source projects shared on it, and you can use and download them for free while abiding by their Licenses.

- Get help from other developers
Developers can ask and answer questions, share codes using the "discussion" feature. As you share your codes, other developers can participate to help you fix bugs, improve project features and quality. 

- Use Github Pages to build your websites
GitHub Pages provides a static web hosting service that fetches HTML, CSS, and JavaScript files directly from repositories on GitHub, then builds and publishes the site. 

### Strengths & Weaknesses
  
| Strengths | Weaknesses |
| :--- | :--- |
| -Easy code hosting and writing | -Difficult to use for beginners |
| -Effective project management and team collaboration | -Merge conflicts sometimes occur |


### Tutorial
  
- Installation

- Start a repository 

- Add new collaborators
  
- Create a README file

- Commit & Push & Pull

- More resources


## Google Colab

### Introduction
  
Google Colab is a product from Google Research. It allows anybody to write and execute python code through the browser, and to save notebooks on the cloud. So, you can think of Colab as a Jupyter notebook stored in Google Drive. It requires no set up and has an excellent free version. 

Here is the official website: [https://colab.research.google.com/](https://colab.research.google.com/)

MBAn students will use Google Colab frequently in <MBAn550 Intro To Data Programming> in the summer term, and are likely to use it in the fall term in order to work on Python projects. And we also recommend anyone who is new to Python programming to use Google Colab due to the strengths mentioned below. 
  
### Strengths
  
- Easy to write and execute python code
  
  + All you need to do is to visit the Google Colab page in your browser and log in your google account. Then you can start to write and execute your python code. 
  
  + Colab is shipped with several pre-installed data libraries, such as Numpy, Pandas, Matplotlib. It also provides pre-installed machine learning libraries, including TensorFlow, and PyTorch. Thus, Google Colab is especially well-suited for machine learning and data analysis. 

- Files saved on the cloud
  
  + All of your Google Colab notebooks are saved under your Google Drive account, just like your Google Docs and Google Sheets files. Therefore, you can access to your notebooks from any device with your Google account log-in.
  
  + You can easily share your files through Google Drive. 

- Collaboration
  
  + If you are working with multiple developers on a project, it is great to use Google Colab. Just like collaborating on a Google Docs document, you can co-code with multiple developers using a Google Colab notebook.
  
  + You can share your completed work with other developers.

### Weaknesses
  
- Limited Space & Time
  
  + Google Colab stores files in Google Drive with a free space of 15GB; however, working on bigger datasets requires more space, making it difficult to execute.

- Only for Python coders
