# Epilogue: How we built this project {-}

## Group process {-}

how did you use the class material to make your group more effective

## Dynamics {-}

How did your group handle challenges and change

## Division of work {-}

How did you divide work, leveraged unique strengths of each individual in the team

## Agile work practices {-}

- **User stories**

A user story is the smallest unit of work in an agile project. It helps us understand our users' needs. 
We can outline a user story using a simple sentence: *"As a ___, I want ___ so that ___."* 

Breaking this sentence down, our team identified our users as MBAn students, UM students, UM faculty and incoming employees involved in team collaboration work. Then, we interviewed two users to understand their intent and purpose of using this product. And we created a list of user stories that represented their needs. 
From these user stories, we got valuable feedbacks from our users. For example, we were informed that our user wanted to know the strengths and weaknesses of each tool, so she could compare different tools. And she also wanted advanced guides and tutorials of tools we introduced. Understanding her needs, we adjusted our Table of Content by adding sections of "Strengths and weaknesses" and "More resources". In addition, we made our tutorials easier to understand by adding pictures and tables so that our user could use this book as a teaching material.

- **Project scope changes**
- 
In an agile project, changes are expected and accepted. It's important for our group to manage changes in our project. Whenever the project changed, our group held a meeting to address the changes effectively according to our team charter. First, we clarified what the change was, and then we listed the things to do and divided the tasks. Finally, we also set a deadline and expected deliveries by the deadline. 

## Learning curve {-}

How did you manage the RMarkdown/Git/GitHub complexity and learning curve

## Reflection {-}

What more could you do to become a more effective and productive team in the time left

## Other {-}

Anything else you would like to provide that pertains to your group process and effectiveness
