---
title: "Team collaboration and management softwares"
author: 'Team: Even Better'
date: '2022-07-19'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We plan on making a guide for future MBAn students focused on team collaboration and management software that may be used for team projects. The guide will include three parts: an introductory overview of the contents of our guide, a detailed breakdown of the tools that we have selected to cover, and a final summary of user feedback and suggestions by current MBAn students. 

Below, you will find a preliminary breakdown of the structure of our guide, including the different software/platforms that we plan to cover. For each of the chosen collaboration tools, we plan on providing the following information: an introduction, the main features, and who tends to use the tool. We have also selected one tool from each of four categories, as shown in bold, to provide more detailed information on, which will include a detailed tutorial on installation, how to use the main features, how to troubleshoot common problems, and more. 



## 1 Overview

- 1.1 The common form of team activity in MBAn
- 1.2 The importance of team collaboration
- 1.3 The importance of increasing efficiency of teamwork
- 1.4 The convenience of the team collaboration tool

## 2 Team collaboration tool guidance

- 2.1 Tools for document collaboration and file sharing
    + 2.1.1 **Google Suite (Drive/Docs/Sheets/Slides)**
        a. Introduction
        b. Main features
        c. Who tends to love it?
        d. Tutorial
    + 2.1.2 Dropbox
        a. Introduction
        b. Main features
        c. Who tends to love it?
- 2.2 Tools for programming
    + 2.2.1 **Github**
    + 2.2.2 Colab
- 2.3 Tools for messaging, virtual meeting
    + 2.3.1 **Zoom**
    + 2.3.2 GroupMe
    + 2.3.3 Microsoft Teams
    + 2.3.4 Slack
    + 2.3.5 When2Meet
- 2.4 Tools for project management
    + 2.4.1 **Jira**
    + 2.4.2 Teamwork
    + 2.4.3 Asana
    + 2.4.4 Notion
    + 2.4.5 HHHH testlida

## 3 Summary tables and graphs of user feedback and suggestions
